version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./xrp_bot.db
    volumes:
      - ./:/app
    command: python -m backend.main

  bot:
    build: .
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./:/app
    command: python -m bot.main
