"""add beneficiaries table

Revision ID: 0697b09d6ad7
Revises: d65e92630518
Create Date: 2025-09-16 11:10:46.416005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0697b09d6ad7'
down_revision: Union[str, None] = 'd65e92630518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alias', name='uq_beneficiary_user_alias')
    )
    op.create_index(op.f('ix_beneficiaries_user_id'), 'beneficiaries', ['user_id'], unique=False)
    op.drop_index('ix_transactions_tx_hash', table_name='transactions')
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=True)
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_index('ix_wallets_xrp_address', table_name='wallets')
    op.create_index(op.f('ix_wallets_xrp_address'), 'wallets', ['xrp_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_xrp_address'), table_name='wallets')
    op.create_index('ix_wallets_xrp_address', 'wallets', ['xrp_address'], unique=False)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'], unique=False)
    op.drop_index(op.f('ix_beneficiaries_user_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
