name: Deploy Presentation to GitHub Pages

on:
  push:
    branches: [ main, prod, dev/ces, dev/joe2, dev/sam, dev/Victor2DUSA ]
    paths:
      - 'docs/**'
      - 'presentation/**'
      - '.github/workflows/deploy-presentation.yml'
  pull_request:  # Also trigger on PRs for preview
    branches: [ main ]
    paths:
      - 'presentation/**'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    # Only deploy to Pages from main/prod branches
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install jupyter plotly pandas numpy kaleido pyyaml nbformat

      - name: Install Quarto
        run: |
          # Direct installation method
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.554/quarto-1.4.554-linux-amd64.deb
          sudo dpkg -i quarto-1.4.554-linux-amd64.deb || true
          sudo apt-get install -f -y
          quarto --version

      - name: Build presentation
        run: |
          if [ -f "presentation/xrp-telegram-bot-presentation.qmd" ]; then
            cd presentation

            # Option 1: Try to render with execution disabled
            echo "Attempting to render with code execution..."
            quarto render xrp-telegram-bot-presentation.qmd --to revealjs --execute-params '{"enabled": false}' 2>&1 || {
              echo "Failed with execution. Trying without code execution..."

              # Option 2: Render without executing Python code
              quarto render xrp-telegram-bot-presentation.qmd --to revealjs --no-execute 2>&1 || {
                echo "Still failing. Trying with freeze..."

                # Option 3: Use freeze to prevent re-execution
                quarto render xrp-telegram-bot-presentation.qmd --to revealjs --freeze 2>&1 || {
                  echo "All render attempts failed"
                  exit 1
                }
              }
            }

            cd ..
          else
            echo "Error: presentation/xrp-telegram-bot-presentation.qmd not found"
            exit 1
          fi

      - name: Prepare docs folder
        run: |
          mkdir -p docs/presentation
          cp presentation/xrp-telegram-bot-presentation.html docs/presentation/
          [ -f "presentation/custom.scss" ] && cp presentation/custom.scss docs/presentation/

          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <title>XRP Telegram Bot - Presentation</title>
              <meta charset="utf-8">
              <meta http-equiv="refresh" content="0;URL='presentation/xrp-telegram-bot-presentation.html'" />
            </head>
            <body>
              <p>Loading presentation...</p>
            </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Separate job for build testing on other branches
  test-build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/dev/ces' || github.ref == 'refs/heads/dev/joe2' || github.ref == 'refs/heads/dev/sam' || github.ref == 'refs/heads/dev/Victor2DUSA'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter plotly pandas numpy kaleido pyyaml nbformat
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.554/quarto-1.4.554-linux-amd64.deb
          sudo dpkg -i quarto-1.4.554-linux-amd64.deb || true
          sudo apt-get install -f -y

      - name: Test build presentation
        run: |
          cd presentation

          # Try different rendering approaches
          echo "Attempting render..."
          quarto render xrp-telegram-bot-presentation.qmd --to revealjs --execute-params '{"enabled": false}' || \
          quarto render xrp-telegram-bot-presentation.qmd --to revealjs --no-execute || \
          quarto render xrp-telegram-bot-presentation.qmd --to revealjs --freeze || {
            echo "All attempts failed"
            exit 1
          }

          echo "✅ Presentation builds successfully"
          ls -la *.html
