# .github/workflows/deploy.yml
name: Post-Deploy Health Check

on:
  workflow_dispatch:  # Manual health check only

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
    - name: Health check
      run: |
        max_attempts=10
        attempt=1

        while [ $attempt -le $max_attempts ]; do
          if curl -f https://xrp-bot-api.onrender.com/health; then
            echo "Health check successful!"
            exit 0
          fi

          echo "Attempt $attempt failed, waiting..."
          sleep 10
          attempt=$((attempt + 1))
        done

        echo "Health check failed"
        exit 1
